"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Brain, ArrowRight, CheckCircle2, Lock, Loader2, Info, ChevronDown, ChevronUp, Filter } from "lucide-react";
import Link from "next/link";

export default function CurriculumPage() {
  const [steps, setSteps] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [hoveredStep, setHoveredStep] = useState<string | null>(null);
  const [expandedStep, setExpandedStep] = useState<string | null>(null);
  const [filter, setFilter] = useState<'all' | 'in_progress' | 'completed'>('all');

  useEffect(() => {
    fetchCurriculum();
  }, []);

  const fetchCurriculum = async () => {
    try {
      const token = localStorage.getItem("token");
      const res = await fetch("http://localhost:5001/api/curriculum", {
        headers: { "Authorization": `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setSteps(data);
      }
    } catch (err) {
      console.error("Error fetching curriculum:", err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="h-full flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-8 max-w-4xl mx-auto py-8">
      <div className="flex flex-col gap-2">
        <h1 className="text-3xl font-bold flex items-center gap-3">
          <Brain className="h-8 w-8 text-primary" />
          Learning Path
        </h1>
        <p className="text-muted-foreground text-lg">
          Your personalized curriculum generated by the Diagnostic Agent.
        </p>
      </div>

      {/* Interactive Filter Toggles */}
      <div className="flex items-center gap-2 bg-secondary/30 p-1 rounded-2xl w-fit border border-border">
        <button 
          onClick={() => setFilter('all')}
          className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${filter === 'all' ? 'bg-primary text-primary-foreground shadow-lg' : 'text-muted-foreground hover:text-foreground'}`}
        >
          All Steps
        </button>
        <button 
          onClick={() => setFilter('in_progress')}
          className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${filter === 'in_progress' ? 'bg-primary text-primary-foreground shadow-lg' : 'text-muted-foreground hover:text-foreground'}`}
        >
          In Progress
        </button>
        <button 
          onClick={() => setFilter('completed')}
          className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${filter === 'completed' ? 'bg-primary text-primary-foreground shadow-lg' : 'text-muted-foreground hover:text-foreground'}`}
        >
          Completed
        </button>
      </div>

      <div className="relative border-l-2 border-primary/20 ml-4 md:ml-8 pl-8 space-y-12 pb-12 mt-4">
        {steps
          .filter(step => filter === 'all' || step.status === filter)
          .map((step, index) => (
            <div key={step.id} className="relative">
            {/* Status Icon */}
            <div className={`absolute -left-[41px] top-1 h-6 w-6 rounded-full border-4 border-background flex items-center justify-center ${
              step.status === 'completed' ? 'bg-green-500' : 
              step.status === 'in_progress' ? 'bg-primary' : 'bg-muted'
            }`}>
              {step.status === 'completed' && <CheckCircle2 className="h-4 w-4 text-white" />}
              {step.status === 'in_progress' && <div className="h-2 w-2 rounded-full bg-primary-foreground animate-ping" />}
              {step.status === 'locked' && <Lock className="h-3 w-3 text-muted-foreground" />}
            </div>

            <motion.div 
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.1 }}
              onMouseEnter={() => setHoveredStep(step.id)}
              onMouseLeave={() => setHoveredStep(null)}
              onClick={() => setExpandedStep(expandedStep === step.id ? null : step.id)}
              className={`bg-card border rounded-2xl p-6 transition-all relative group cursor-pointer ${
                step.status === 'in_progress' ? 'border-primary/50 shadow-lg shadow-primary/5' : 
                step.status === 'locked' ? 'opacity-50 grayscale pointer-events-none' : 'border-border hover:border-primary/30'
              }`}
            >
              <div className="absolute right-6 top-6 text-muted-foreground group-hover:text-primary transition-colors">
                {expandedStep === step.id ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
              </div>

              <AnimatePresence>
                {hoveredStep === step.id && step.previewText && (
                  <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: 10 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 10 }}
                    className="absolute -top-32 left-0 right-0 z-50 p-4 bg-popover border border-border rounded-xl shadow-2xl pointer-events-none"
                  >
                    <div className="flex items-center gap-2 mb-2">
                      <Info className="h-3 w-3 text-primary" />
                      <span className="text-[10px] font-bold uppercase text-primary">Content Preview</span>
                    </div>
                    <p className="text-xs text-muted-foreground line-clamp-4 italic">
                      "{step.previewText}"
                    </p>
                    <div className="absolute -bottom-2 left-1/2 -translate-x-1/2 w-4 h-4 bg-popover border-b border-r border-border rotate-45" />
                  </motion.div>
                )}
              </AnimatePresence>

              <div className={`inline-flex px-3 py-1 rounded-full text-xs font-bold mb-4 ${
                step.status === 'completed' ? 'bg-green-500/10 text-green-500' : 
                step.status === 'in_progress' ? 'bg-primary/10 text-primary' : 'bg-muted/50 text-muted-foreground'
              }`}>
                {step.status.replace('_', ' ').toUpperCase()}
              </div>
              
              <h3 className={`text-xl font-bold mb-2 ${step.status === 'in_progress' ? 'text-2xl' : ''}`}>
                {step.title}
              </h3>
              
              <p className="text-muted-foreground mb-6">
                {step.description}
              </p>

              {/* Expanded Content */}
              <AnimatePresence>
                {expandedStep === step.id && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="overflow-hidden"
                  >
                    <div className="pt-4 border-t border-border mt-4 space-y-4">
                      {step.fullText && (
                        <div>
                          <h4 className="text-xs font-bold uppercase text-primary mb-2">Detailed Summary</h4>
                          <p className="text-sm text-muted-foreground leading-relaxed">
                            {step.fullText}
                          </p>
                        </div>
                      )}
                      {step.formulas && step.formulas.length > 0 && (
                        <div>
                          <h4 className="text-xs font-bold uppercase text-primary mb-2">Key Formulas</h4>
                          <div className="flex flex-wrap gap-2">
                            {step.formulas.map((f: string, i: number) => (
                              <code key={i} className="px-2 py-1 bg-secondary rounded text-xs font-mono">
                                {f}
                              </code>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {step.status === 'in_progress' && (
                <div className="flex gap-4">
                  <Link 
                    href={step.type === 'quiz' ? '/quizzes' : '/chat'} 
                    className="bg-primary text-primary-foreground px-6 py-2.5 rounded-xl font-semibold hover:opacity-90 transition-opacity flex items-center gap-2"
                  >
                    {step.type === 'quiz' ? 'Take Quiz' : 'Continue Learning'} <ArrowRight className="h-4 w-4" />
                  </Link>
                </div>
              )}
            </motion.div>
          </div>
        ))}
      </div>
    </div>
  );
}
